import { defineStore } from 'pinia'

export const useCharacterStore = defineStore('character', {
  state: () => ({
    OC: [
      {
        name: '瑟琳.阿特伍德',
        engName: 'Selene.Atwood',
        sex: 'female',
        age: 14,
        height: 153,
        birthday: '10/30',
        category: '企劃',
        world: 'SLC',
        world_link: 'https://sanlooncollege.wixsite.com/sunandmoon',
        intro: '妹',
        icon: 'https://images.plurk.com/4aotZsaXbKHdYQeSe6M7zb.png',
        is_married: false
      },
      {
        name: '林恩.阿特伍德',
        engName: 'Liam.Atwood',
        sex: 'male',
        age: 15,
        height: 168,
        birthday: '11/3',
        category: '企劃',
        world: 'SLC',
        world_link: 'https://sanlooncollege.wixsite.com/sunandmoon',
        intro: '兄',
        icon: 'https://images.plurk.com/5yLf9NStIO9hP7ZqhirzqJ.png',
        is_married: false
      },
      {
        name: '中野伸司',
        engName: 'Nakano Shinji',
        sex: 'male',
        age: 15,
        height: 175,
        birthday: '12/7',
        category: '企劃',
        world: 'FK',
        world_link: 'https://nameless2023.wixsite.com/fukigi-koko',
        intro: '高中生',
        icon: 'https://images.plurk.com/3OvCnvmwJYJJyyS2WRUKwF.png',
        is_married: true
      },
      {
        name: '江離',
        engName: 'Jiang Li',
        sex: 'male',
        age: 24,
        height: 181,
        birthday: '09/28',
        category: '企劃',
        world: '柔桑志異',
        world_link: 'https://polyanthusonly.wixsite.com/rszhiyi',
        intro: '朽木',
        icon: 'https://images.plurk.com/1uGEuuPSiuSvaG4jLPdjb9.png',
        is_married: false
      },
      {
        name: '月蝕',
        engName: '월식',
        sex: 'male',
        age: 27,
        height: 175,
        birthday: '11/8',
        category: '企劃',
        world: 'DR',
        world_link: 'https://wwwf07ww.wixsite.com/dreamland-roaming',
        intro: '網遊補師',
        icon: 'https://images.plurk.com/7lqlbNEpSBjCeb9AGi7lFb.png',
        is_married: false
      },
      {
        name: '凱倫',
        engName: 'Kaylen',
        sex: 'female',
        age: 27,
        height: 177,
        birthday: '04/15',
        category: '',
        world: '',
        world_link: '',
        intro: '蛇蠍美人',
        icon: 'https://images.plurk.com/70QFpHvCjtpOu7XJNbhBN5.png',
        is_married: false
      },
      {
        name: '路西恩',
        engName: 'Lucian',
        sex: 'male',
        age: 25,
        height: 183,
        birthday: '07/23',
        category: '企劃',
        world: 'IE',
        world_link: 'https://ventureseafaring2023.wixsite.com/seamark',
        intro: '性格豪爽的軍人',
        icon: 'https://images.plurk.com/7xshwtnLyJOELT4P3ZUgJ5.png ',
        is_married: false
      },
      {
        name: '池田蒼一',
        engName: 'Ikeda Aoi',
        sex: 'male',
        age: 16,
        height: 178,
        birthday: '06/21',
        category: '企劃',
        world: 'CSG',
        world_link: 'https://su2022.wixsite.com/championshipgame',
        intro: '看起來像不良少年的高中生',
        icon: 'https://images.plurk.com/4IPFGQx4k85W8WnPe0hsf0.png',
        is_married: false
      },
      {
        name: '小林夏生',
        engName: 'kobayasi natsuki',
        sex: 'female',
        age: 21,
        height: 165,
        birthday: '07/07',
        category: '企劃',
        world: 'CSG',
        world_link: 'https://su2022.wixsite.com/championshipgame',
        intro: '居酒屋打工少女',
        icon: 'https://images.plurk.com/lRELzoJCOuIgdCTZv0wVn.png',
        is_married: false
      },
      {
        name: '飛鳥明音',
        engName: 'Asuka minto',
        sex: 'female',
        age: 29,
        height: 162,
        birthday: '10/23',
        category: '企劃',
        world: 'CSG',
        world_link: 'https://su2022.wixsite.com/championshipgame',
        intro: '音樂老師',
        icon: 'https://images.plurk.com/3uGtGSE19IAt82b23ArBUc.png',
        is_married: false
      },
      {
        name: 'ハル',
        engName: 'Haru',
        sex: 'Angel',
        age: 15,
        height: 158,
        birthday: '02/09',
        category: '企劃',
        world: '梧柊',
        world_link: 'https://www.plurk.com/wuwu_app',
        intro: '†天使†',
        icon: 'https://images.plurk.com/519vMbymJbA0Q23UAJsJbO.png',
        is_married: false
      },
      {
        name: '安靜',
        engName: 'An Jing',
        sex: 'female',
        age: 19,
        height: 149,
        birthday: '04/25',
        category: '企劃',
        world: 'FS2',
        world_link: 'https://fs-team.wixsite.com/futurestar2',
        intro: '追星少女',
        icon: 'https://images.plurk.com/74HL8A4k5T99t9H3WL2YVT.png',
        is_married: false
      },
      {
        name: '宮川冬雪',
        engName: 'Miyagawa Fuyuki',
        sex: 'female',
        age: 19,
        height: 173,
        birthday: '12/25',
        category: '企劃',
        world: 'FS2',
        world_link: 'https://fs-team.wixsite.com/futurestar2',
        intro: '王子系女子',
        icon: 'https://images.plurk.com/rc38kOcqnT2Ft9AKiYxsY.png',
        is_married: false
      },
      {
        name: '米契爾',
        engName: 'Mitchell',
        sex: 'male',
        age: 28,
        height: 173,
        birthday: '09/25',
        category: '企劃',
        world: 'MM',
        world_link: 'https://www.plurk.com/mizmic',
        intro: '大學教授',
        icon: 'https://images.plurk.com/583LVX0a7npg5DF4VSVmwC.png',
        is_married: false
      },
      {
        name: '艾德里安.菲茨傑拉德',
        engName: 'Adrian.Fitzgerald',
        sex: 'male',
        age: 24,
        height: 190,
        birthday: '03/28',
        category: '企劃',
        world: 'TL',
        world_link: 'https://korouns.wixsite.com/website-2',
        intro: '俱樂部員工',
        icon: 'https://images.plurk.com/W6Pvtt0BDvdeTrlaLyqFb.png',
        is_married: true
      },
      {
        name: '河原靖也',
        engName: 'Kawahara Yasunari',
        sex: 'male',
        age: 29,
        height: 177,
        birthday: '03/17',
        category: 'TRPG',
        world: '晩夏に凍みゆく',
        world_link: '',
        intro: '大正時代的醫生',
        icon: 'https://images.plurk.com/56YvOlfZnwKhbCvPY6CJlT.png',
        is_married: false
      },
      {
        name: '白神悠人',
        engName: 'Shiraga Yuto',
        sex: 'male',
        age: 24,
        height: 181,
        birthday: '10/10',
        category: 'TRPG',
        world: '片鱗',
        world_link: '',
        intro: '溫柔大狗',
        icon: 'https://images.plurk.com/6rpelTQJAptjvmoG0nke5M.png',
        is_married: false
      },
      {
        name: '菲尼克斯',
        engName: 'Phoenix',
        sex: 'male',
        age: 50,
        height: 149,
        birthday: '04/04',
        category: '企劃',
        world: 'Elysium',
        world_link: 'https://www.plurk.com/Elysium_000',
        intro: '少根筋的吸血鬼',
        icon: 'https://images.plurk.com/1dHgszHnATa67R6CuQ1ryh.png',
        is_married: false
      },
      {
        name: '雨宮葵',
        engName: 'Amamia Aoi',
        sex: 'female',
        age: 16,
        height: 167,
        birthday: '05/20',
        category: '',
        world: '津見川東高等学校(NPC)',
        world_link: 'https://87planmaster.wixsite.com/tsumikawahigashi-h',
        intro: '水泳部主將',
        icon: 'https://images.plurk.com/5HPrWu6aIJ96iATRxbpx7D.png',
        is_married: false
      },
      {
        name: '奧菲莉亞',
        engName: 'Ophelia',
        sex: 'female',
        age: 17,
        height: 169,
        birthday: '01/20',
        category: '',
        world: '',
        world_link: '',
        intro: '懷抱禁斷之戀的少女',
        icon: 'https://images.plurk.com/7MBF8QOLYqb5ynxoYxbnno.png',
        is_married: false
      },
      {
        name: '里歐瑞克.凱登',
        engName: 'Leoric.Caden',
        sex: 'male',
        age: 35,
        height: 181,
        birthday: '07/21',
        category: '',
        world: '',
        world_link: '',
        intro: '現役神父',
        icon: 'https://images.plurk.com/EqYczrz8ll3ZmcymABK5D.png',
        is_married: true
      },
      {
        name: '阿克',
        engName: 'Acker',
        sex: 'male',
        age: 19,
        height: 177,
        birthday: '08/21',
        category: '企劃',
        world: 'GE',
        world_link: 'https://geraldseyeball.wixsite.com/geraldseyeball',
        intro: '海盜',
        icon: 'https://images.plurk.com/3uUDr0mU7UOhPIG1XuB0V2.png',
        is_married: false
      }
    ]
  })
})
